name: bibliotech-grobid
services:
  bibliotech-grobid:
    container_name: bibliotech-grobid
    init: true
    ulimits:
      core: 0
    ports:
      - 127.0.0.1:8070:8070
    image: lfoppiano/grobid:0.8.0
    networks:
      - bibliotech

networks:
  bibliotech:
    name: bibliotech-network
