name: bibliotech-python

services:
  bibliotech_python:
    container_name: bibliotech_python
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - $CA_CERTS_PATH:/bibliotech_data/kibana/config/certs
      - $PDF_NEW_PATH:/bibliotech_data/pdf_new
      - $PDF_INGESTION_FAILED:/bibliotech_data/pdf_ingestion_failed
      - $PDF_COLLECTION_PATH:/bibliotech_data/pdf_collection
      - $TEI_XML_COLLECTION_PATH:/bibliotech_data/tei_xml_collection
      - $DOCUMENTS_PATH:/bibliotech_data/documents
    environment:
      - PARQUET_COMPRESSION=${PARQUET_COMPRESSION}
      - ELASTICSEARCH_URL=https://es:9200
      - ELASTICSEARCH_INDEX=${ELASTICSEARCH_INDEX}
      - SCAN_REFRESH_RATE=${SCAN_REFRESH_RATE}
      - LOG_LEVEL=${LOG_LEVEL}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - KIBANA_PASSWORD=${KIBANA_PASSWORD}
    networks:
      - bibliotech

networks:
  bibliotech:
    name: bibliotech-network
